import json
from typing import List, Dict, Any

class PolicyGenerator:
    """Generate least-privilege policies based on observed usage"""

    @staticmethod
    def generate_aws_json(identity_name: str, used_actions: List[str]) -> Dict[str, Any]:
        """
        Groups actions by service and creates a clean IAM policy.
        """
        if not used_actions:
            return {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Deny",
                        "Action": "*",
                        "Resource": "*",
                        "Condition": {"StringEquals": {"aws:PrincipalTag/PrivilegePredict": "Restricted"}}
                    }
                ]
            }

        # Group actions by service (e.g., s3:GetObject -> s3)
        service_map = {}
        for action in used_actions:
            if ':' in action:
                service = action.split(':')[0]
                if service not in service_map:
                    service_map[service] = []
                service_map[service].append(action)
            else:
                # Handle cases without colons if they exist
                if "other" not in service_map:
                    service_map["other"] = []
                service_map["other"].append(action)

        statements = []
        for service, actions in service_map.items():
            statements.append({
                "Sid": f"Allow{service.capitalize()}Actions",
                "Effect": "Allow",
                "Action": sorted(list(set(actions))),
                "Resource": "*" # Scope to * for MVP, Phase 3 could handle ARN resource mapping
            })

        return {
            "Version": "2012-10-17",
            "Statement": statements
        }

    @staticmethod
    def generate_terraform(identity_name: str, json_policy: Dict[str, Any]) -> str:
        """
        Wraps the JSON policy into a Terraform aws_iam_policy resource.
        """
        policy_json_str = json.dumps(json_policy, indent=2)
        safe_name = identity_name.replace(':', '-').replace('/', '-').lower()
        
        hcl = f"""resource "aws_iam_policy" "{safe_name}_least_privilege" {{
  name        = "{safe_name}-least-privilege"
  description = "Least-privilege policy generated by PrivilegePredict based on observed usage"

  policy = <<EOF
{policy_json_str}
EOF
}}
"""
        return hcl
